from pathlib import Path
import sys
p=Path(sys.argv[1]);s=p.read_text()
s=s.replace('<title>Undead Afterdark V8 - Overhaul</title>','<title>Undead Afterdark V9 - Animated Controls</title>')
s=s.replace("  .touch{\n    position:absolute;bottom:22px;left:0;right:0;display:flex;\n    justify-content:space-between;align-items:flex-end;padding:0 24px;\n    pointer-events:none;\n  }", "  .touch{display:none!important}\n  #dashBtn{display:none!important}")
s=s.replace('WASD to move, mouse to aim, hold left click to fire, Space to dash.','WASD to move, mouse to aim, hold left click to fire.')
s=s.replace("    {id:'dash',name:'Dash Upgrade',base:300,desc:'Dash recharges 10% faster.',scale:1.4,buy(){\n      state.upgrades.dash++;\n    }},\n","")
s=s.replace("    if(e.code==='Space'){e.preventDefault();dash()}\n","")
s=s.replace("    fireCd:0,dashCd:0,dashMax:3.5,dashTime:0,invuln:0,aimX:1,aimY:0\n  };", "    fireCd:0,dashCd:0,dashMax:3.5,dashTime:0,invuln:0,aimX:1,aimY:0,\n    animT:0,moveMag:0,shotKick:0,hurtAnim:0\n  };")
s=s.replace("weapon:'sidearm',ammo:12,reloading:false,reloadTimer:0,fireCd:0,dashCd:0,dashTime:0,invuln:0\n", "weapon:'sidearm',ammo:12,reloading:false,reloadTimer:0,fireCd:0,dashCd:0,dashTime:0,invuln:0,animT:0,moveMag:0,shotKick:0,hurtAnim:0\n")
s=s.replace("hue:boss?0:hueBase+(Math.random()-.5)*18,\n      swing:Math.random()*Math.PI*2\n", "hue:boss?0:hueBase+(Math.random()-.5)*18,\n      swing:Math.random()*Math.PI*2,animT:Math.random()*Math.PI*2,attackAnim:0\n")
s=s.replace("    player.fireCd=1/getRate();\n    muzzleFX();", "    player.fireCd=1/getRate();\n    player.shotKick=.11;\n    muzzleFX();")
s=s.replace("    player.invuln=Math.max(0,player.invuln-dt);\n", "    player.invuln=Math.max(0,player.invuln-dt);\n    player.shotKick=Math.max(0,player.shotKick-dt);\n    player.hurtAnim=Math.max(0,player.hurtAnim-dt);\n")
s=s.replace("    const ml=Math.hypot(mx,my)||1; mx/=ml; my/=ml;\n    let sp=getSpeed()*(player.dashTime>0?3.2:1);\n    if(player.dashTime>0) player.dashTime-=dt;\n    moveWithMapCollision(player,mx*sp*dt,my*sp*dt,player.r+3);\n", "    const rawMove=Math.min(1,Math.hypot(mx,my));\n    const ml=Math.hypot(mx,my)||1; mx/=ml; my/=ml;\n    player.moveMag=rawMove;\n    player.animT += dt*(rawMove>.03 ? 9.5+getSpeed()/55 : 2.2);\n    let sp=getSpeed();\n    moveWithMapCollision(player,mx*sp*dt,my*sp*dt,player.r+3);\n")
s=s.replace("      z.hitCd=Math.max(0,z.hitCd-dt);\n      z.hitFlash=Math.max(0,(z.hitFlash||0)-dt);\n      const dx=player.x-z.x,dy=player.y-z.y,l=Math.hypot(dx,dy)||1;\n      const pursuitSpeed=z.speed*(z.catchup||1);\n      const zx=dx/l*pursuitSpeed*dt, zy=dy/l*pursuitSpeed*dt;\n      moveWithMapCollision(z,zx,zy,Math.max(10,z.r*.55));\n      const touchDist=Math.hypot(player.x-z.x,player.y-z.y);\n      if(touchDist<z.r+player.r+2 && z.hitCd<=0 && player.invuln<=0){\n        z.hitCd=.7;\n", "      z.hitCd=Math.max(0,z.hitCd-dt);\n      z.hitFlash=Math.max(0,(z.hitFlash||0)-dt);\n      z.attackAnim=Math.max(0,(z.attackAnim||0)-dt);\n      const dx=player.x-z.x,dy=player.y-z.y,l=Math.hypot(dx,dy)||1;\n      const pursuitSpeed=z.speed*(z.catchup||1);\n      z.animT += dt*(3.6+pursuitSpeed/34);\n      const zx=dx/l*pursuitSpeed*dt, zy=dy/l*pursuitSpeed*dt;\n      moveWithMapCollision(z,zx,zy,Math.max(10,z.r*.55));\n      const touchDist=Math.hypot(player.x-z.x,player.y-z.y);\n      if(touchDist<z.r+player.r+2 && z.hitCd<=0 && player.invuln<=0){\n        z.hitCd=.7;\n        z.attackAnim=.23;\n")
s=s.replace("        player.hp-=dmg;\n", "        player.hp-=dmg;\n        player.hurtAnim=.16;\n")
a=s.index('  function drawZombie(z){');b=s.index('\n  function drawParticles(){',a)
z=r'''  function drawZombie(z){
    const t=z.animT||0,speedMul=z.kind==='runner'?1.35:(z.kind==='crawler'?1.55:(z.kind==='brute'?.78:1));
    const stride=Math.sin(t*speedMul),bob=Math.abs(Math.sin(t*speedMul))*(z.kind==='brute'?2.5:1.6),attack=z.attackAnim>0?Math.sin((1-z.attackAnim/.23)*Math.PI):0;
    const ang=Math.atan2(player.y-z.y,player.x-z.x),r=z.r;
    const palette={CITY:['#5b704d','#87956c'],FOREST:['#4f6b43','#7e8b61'],SWAMP:['#536f48','#819260'],DESERT:['#75684b','#9b8a62'],INDUSTRIAL:['#50655a','#7e8a76']}[z.biome]||['#556b48','#849269'];
    const body=z.boss?'#7e252c':palette[0],skin=z.boss?'#b6383d':palette[1];
    ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(z.x+4,z.y+r*.72+7,r*1.05,r*.42,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(z.x,z.y-bob);ctx.rotate(ang);ctx.globalAlpha=z.hitFlash>0?.72:1;
    if(z.kind==='crawler'){ctx.rotate(stride*.045);ctx.strokeStyle='#394638';ctx.lineWidth=5;ctx.lineCap='round';for(const sy of[-1,1]){ctx.beginPath();ctx.moveTo(-r*.15,sy*r*.28);ctx.lineTo(-r*(.82+.10*stride),sy*r*(.70-.08*stride));ctx.stroke();ctx.beginPath();ctx.moveTo(r*.18,sy*r*.28);ctx.lineTo(r*(.58-.08*stride),sy*r*(.72+.08*stride));ctx.stroke()}ctx.fillStyle=body;ctx.beginPath();ctx.ellipse(0,0,r*.98,r*.60,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=skin;ctx.beginPath();ctx.arc(r*(.72+.08*attack),0,r*.40,0,Math.PI*2);ctx.fill()}
    else{const wide=z.kind==='brute'?1.18:(z.kind==='runner'?.72:1),legSwing=stride*r*(z.kind==='runner'?.52:.34),armSwing=-stride*r*(z.kind==='runner'?.58:.36);ctx.rotate((z.kind==='runner'?-0.16:-0.04)+attack*.08);ctx.strokeStyle=z.boss?'#5b151a':'#344335';ctx.lineWidth=Math.max(5,r*.20);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-r*.28,-r*.27);ctx.lineTo(-r*.83,-r*.48+legSwing);ctx.moveTo(-r*.28,r*.27);ctx.lineTo(-r*.83,r*.48-legSwing);ctx.stroke();ctx.strokeStyle=z.boss?'#682027':'#495744';ctx.lineWidth=Math.max(5,r*.18);const reach=attack*r*.55;ctx.beginPath();ctx.moveTo(r*.12,-r*.42);ctx.lineTo(r*.70+reach,-r*.68+armSwing);ctx.moveTo(r*.12,r*.42);ctx.lineTo(r*.70+reach,r*.68-armSwing);ctx.stroke();ctx.fillStyle=body;ctx.beginPath();ctx.ellipse(0,0,r*.86*wide,r*.68,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(20,25,20,.34)';ctx.beginPath();ctx.ellipse(-r*.15,0,r*.33*wide,r*.58,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=skin;ctx.beginPath();ctx.arc(r*(.68+.10*attack),0,r*(z.kind==='brute'?.43:.36),0,Math.PI*2);ctx.fill();if(z.kind==='brute'){ctx.strokeStyle='#2e342d';ctx.lineWidth=4;ctx.beginPath();ctx.arc(r*.68,0,r*.49,-.8,.8);ctx.stroke()}}
    ctx.fillStyle=z.boss?'#ffd0a0':'#d8d78a';ctx.beginPath();ctx.arc(r*.91,-r*.11,Math.max(1.5,r*.07),0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(r*.91,r*.11,Math.max(1.5,r*.07),0,Math.PI*2);ctx.fill();if(z.boss){ctx.strokeStyle='rgba(255,74,85,.65)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-r*.55,-r*.2);ctx.lineTo(r*.25,-r*.08);ctx.moveTo(-r*.45,r*.25);ctx.lineTo(r*.15,r*.12);ctx.stroke()}ctx.restore();if(z.boss||z.hp<z.maxHp*.98){const w=r*2.2;ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(z.x-w/2,z.y-r-18,w,5);ctx.fillStyle=z.boss?'#ff4653':'#d45b5b';ctx.fillRect(z.x-w/2,z.y-r-18,w*Math.max(0,z.hp/z.maxHp),5)}if(z.boss){ctx.fillStyle='#fff';ctx.font='800 12px system-ui';ctx.textAlign='center';ctx.fillText('WARDEN',z.x,z.y-r-24)}
  }
'''
s=s[:a]+z+s[b:]
a=s.index("    const ang=Math.atan2(player.aimY,player.aimX);\n    ctx.save();ctx.translate(player.x,player.y);ctx.rotate(ang);const flash=player.invuln>0;");b=s.index("    ctx.strokeStyle='rgba(255,255,255,.22)'",a)
pl=r'''    const ang=Math.atan2(player.aimY,player.aimX),movePulse=Math.sin(player.animT||0),moveAmt=player.moveMag||0,bob=Math.abs(movePulse)*1.8*moveAmt,recoil=(player.shotKick||0)/.11,reloadPhase=player.reloading?1-Math.max(0,player.reloadTimer)/Math.max(.001,getReload()):0,reloadDip=player.reloading?Math.sin(reloadPhase*Math.PI)*.48:0,hurt=(player.hurtAnim||0)>0;
    ctx.save();ctx.translate(player.x,player.y-bob);ctx.rotate(ang);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(-2,7+bob,18,11,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=hurt?'#b76060':'#20272c';ctx.lineWidth=7;ctx.lineCap='round';const leg=movePulse*7*moveAmt;ctx.beginPath();ctx.moveTo(-7,7);ctx.lineTo(-13,18+leg);ctx.moveTo(4,7);ctx.lineTo(9,18-leg);ctx.stroke();ctx.fillStyle=hurt?'#9c5555':'#3f4b54';ctx.beginPath();ctx.ellipse(-1,0,12,14,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20262b';ctx.fillRect(-7,-8,13,15);ctx.fillStyle='#c79873';ctx.beginPath();ctx.arc(-5,-10,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2c241f';ctx.beginPath();ctx.arc(-7,-13,5,Math.PI,Math.PI*2);ctx.fill();const armSwing=movePulse*3.5*moveAmt*(player.reloading?.25:1);ctx.strokeStyle='#b98968';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(4,-6);ctx.lineTo(14-recoil*3,-3+armSwing+reloadDip*8);ctx.moveTo(3,5);ctx.lineTo(15-recoil*3,2-armSwing+reloadDip*9);ctx.stroke();ctx.save();ctx.translate(-recoil*5,reloadDip*7);ctx.rotate(reloadDip*.55);ctx.strokeStyle='#11171b';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(28,0);ctx.stroke();ctx.strokeStyle='#737d84';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(24,0);ctx.lineTo(34,0);ctx.stroke();ctx.restore();ctx.restore();
'''
s=s[:a]+pl+s[b:]
a=s.index('  // mobile controls\n');b=s.index("  document.getElementById('startBtn').onclick=()=>{",a)
controls=r'''  // Mobile controls: invisible twin-stick zones directly on the canvas.
  let moveTouchId=null,fireTouchId=null,moveOriginX=0,moveOriginY=0,fireOriginX=0,fireOriginY=0;
  const byId=(list,id)=>{if(id===null||!list)return null;for(let i=0;i<list.length;i++)if(list[i].identifier===id)return list[i];return null},changedHas=(e,id)=>!!byId(e.changedTouches,id);
  const setMoveFromTouch=t=>{let dx=(t.clientX-moveOriginX)/62,dy=(t.clientY-moveOriginY)/62,l=Math.hypot(dx,dy);if(l<.07){dx=0;dy=0;l=0}if(l>1){dx/=l;dy/=l}state.joy={x:dx,y:dy,active:true}};
  const setAimFromTouch=t=>{let dx=t.clientX-fireOriginX,dy=t.clientY-fireOriginY,l=Math.hypot(dx,dy);if(l>10){dx/=l;dy/=l;state.fireAim={x:dx,y:dy,active:true};player.aimX=dx;player.aimY=dy}};
  const resetMove=()=>{moveTouchId=null;state.joy={x:0,y:0,active:false}},resetFire=()=>{fireTouchId=null;state.fireHeld=false;state.fireAim.active=false};
  canvas.addEventListener('touchstart',e=>{if(!state.running||state.paused)return;e.preventDefault();for(const t of e.changedTouches){if(t.clientY<70)continue;if(t.clientX<W*.48&&moveTouchId===null){moveTouchId=t.identifier;moveOriginX=t.clientX;moveOriginY=t.clientY;state.joy={x:0,y:0,active:true}}else if(t.clientX>W*.52&&fireTouchId===null){fireTouchId=t.identifier;fireOriginX=t.clientX;fireOriginY=t.clientY;state.fireHeld=true;setAimFromTouch(t)}}},{passive:false});
  canvas.addEventListener('touchmove',e=>{if(!state.running||state.paused)return;e.preventDefault();const mt=byId(e.touches,moveTouchId);if(mt)setMoveFromTouch(mt);const ft=byId(e.touches,fireTouchId);if(ft)setAimFromTouch(ft)},{passive:false});
  const finishTouches=e=>{if(changedHas(e,moveTouchId))resetMove();if(changedHas(e,fireTouchId))resetFire()};canvas.addEventListener('touchend',e=>{e.preventDefault();finishTouches(e)},{passive:false});canvas.addEventListener('touchcancel',e=>{e.preventDefault();finishTouches(e)},{passive:false});

'''
s=s[:a]+controls+s[b:]
s=s.replace('This build adds an infinite chunked world, random biomes, full collision, 2x zombies, horde catch-up/recycling, the survivor model, shop, weapons, perks, armor, cash, and boss waves.','V9 animation build: invisible twin-stick controls, no dash UI, animated survivor movement/fire/reload, and animated zombie locomotion/attacks.')
p.write_text(s)
